enum HealthEventType {
  profileUpdated,
  healthCheckInRecorded,
  dailyHealthRecorded,
  waterLogged,
  waterTargetUpdated,
  waterGoalReached,
  sleepSummaryUpdated,
  sleepRiskDetected,
  stressRecorded,
  nutritionUpdated,
  nutritionProfileUpdated,
  foodScanConfirmedConsumed,
  mealPlanUpdated,
  scheduleUpdated,
  taskCompleted,
  taskSkipped,
  taskRescheduled,
  goalUpdated,
  goalCompleted,
  authIdentityChanged,
  cloudSyncCompleted,
}

extension HealthEventTypeWireName on HealthEventType {
  String get wireName => switch (this) {
        HealthEventType.profileUpdated => 'profile.updated',
        HealthEventType.healthCheckInRecorded => 'health_checkin.recorded',
        HealthEventType.dailyHealthRecorded => 'daily_health.recorded',
        HealthEventType.waterLogged => 'water.logged',
        HealthEventType.waterTargetUpdated => 'water.target_updated',
        HealthEventType.waterGoalReached => 'water.goal_reached',
        HealthEventType.sleepSummaryUpdated => 'sleep.summary_updated',
        HealthEventType.sleepRiskDetected => 'sleep.risk_detected',
        HealthEventType.stressRecorded => 'stress.recorded',
        HealthEventType.nutritionUpdated => 'nutrition.updated',
        HealthEventType.nutritionProfileUpdated => 'nutrition.profile_updated',
        HealthEventType.foodScanConfirmedConsumed =>
          'food_scan.confirmed_consumed',
        HealthEventType.mealPlanUpdated => 'meal_plan.updated',
        HealthEventType.scheduleUpdated => 'schedule.updated',
        HealthEventType.taskCompleted => 'task.completed',
        HealthEventType.taskSkipped => 'task.skipped',
        HealthEventType.taskRescheduled => 'task.rescheduled',
        HealthEventType.goalUpdated => 'goal.updated',
        HealthEventType.goalCompleted => 'goal.completed',
        HealthEventType.authIdentityChanged => 'auth.identity_changed',
        HealthEventType.cloudSyncCompleted => 'cloud_sync.completed',
      };
}
