name: nano_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^3.3.1

  # Navigation
  go_router: ^17.2.3

  # Network
  dio: ^5.9.2
  connectivity_plus: ^7.1.1

  # Local Storage
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5

  # Supabase
  supabase_flutter: ^2.12.4
  qr_flutter: ^4.1.0

  # Env
  flutter_dotenv: ^6.0.1
  google_generative_ai: ^0.4.7

  # Settings Feature Dependencies
  local_auth: ^2.2.0
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  flutter_local_notifications: 19.5.0
  timezone: 0.10.1
  flutter_timezone: 5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  rename: ^3.0.2
  mockito: ^5.4.4
  build_runner: ^2.4.8
  sqflite_common_ffi: ^2.3.6
  rename_app: ^1.6.6

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/avatars/
    - assets/images/backgrounds/
    - assets/images/banners/
    - assets/images/foods/
    - assets/images/logos/
    - assets/images/Nabi/
    - assets/images/Nabi/chat/
    - assets/images/Nabi/core/
    - assets/images/Nabi/daily/
    - assets/images/Nabi/engagement/
    - assets/images/Nabi/future/
    - assets/images/Nabi/onboarding/
    - assets/images/Nabi/progress/
    - assets/images/Nabi/system/
    - assets/images/symptoms/
    - assets/icons/
    - assets/icons/custom/
    - assets/icons/filled/
    - assets/icons/health/
    - assets/icons/nutrition/
    - assets/icons/outlined/
    - assets/illustrations/
    - assets/illustrations/ai/
    - assets/illustrations/auth/
    - assets/illustrations/dashboard/
    - assets/illustrations/health/
    - assets/illustrations/onboarding/
    - assets/animations/
    - assets/animations/flare/
    - assets/animations/lottie/
    - assets/animations/rive/
    - assets/audio/
    - assets/audio/meditation/
    - assets/audio/notification/
    - assets/audio/sleep/
    - assets/config/
    - assets/config/Nabi/
    - assets/json/
    - assets/json/config/
    - assets/json/mock/
    - assets/json/seed/
    - assets/svg/
    - assets/svg/icons/
    - assets/svg/illustrations/
    - assets/svg/logos/
    - assets/translations/
    - assets/videos/
    - assets/videos/exercise/
    - assets/videos/onboarding/
    - assets/videos/tutorial/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Logo.jpg"
