import 'nabi_notification_models.dart';

abstract final class NabiNotificationCatalog {
  static const _free = {'free'};
  static const _guestAndFree = {'guest', 'free'};
  static const _plusMonthly = {'plus_monthly'};
  static const _allCare = {
    'guest',
    'free',
    'plus_monthly',
    'plus_yearly',
    'family_plus',
  };
  static const _memberReward = {
    'free',
    'plus_monthly',
    'plus_yearly',
    'family_plus',
  };

  static const definitions = <NabiNotificationDefinition>[
    NabiNotificationDefinition(
      id: 'NBI-FREE-001', contentVersion: 1,
      category: NabiNotificationCategory.contextual, priority: 1000,
      policyKey: 'free_plan_limit', audiences: _guestAndFree,
      title: 'Mình tiếp tục hành trình nhé',
      body: 'Nabi có thể mở tiếp kế hoạch phù hợp với bạn.',
      emotionKey: 'encouraging', primaryLabel: 'Xem gói Plus',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_compare', planCode: 'plus',
        billingCycle: 'monthly', focus: 'meal_plan'),
      secondaryLabel: 'Để sau',
      secondaryDestination: NabiNotificationDestination(actionKey: 'defer'),
      channels: {NabiNotificationChannel.inApp}, proactive: false, upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-FREE-002', contentVersion: 1,
      category: NabiNotificationCategory.contextual, priority: 1000,
      policyKey: 'free_chat_limit', audiences: _free,
      title: 'Nabi vẫn ở đây cùng bạn',
      body: 'Bạn còn 1 lượt hỏi miễn phí hôm nay hoặc có thể xem quyền lợi Plus.',
      emotionKey: 'concerned', primaryLabel: 'Xem quyền lợi Plus',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_compare', planCode: 'plus',
        billingCycle: 'monthly', focus: 'ai_chat'),
      secondaryLabel: 'Quay lại sau',
      secondaryDestination: NabiNotificationDestination(actionKey: 'defer'),
      channels: {NabiNotificationChannel.inApp}, proactive: false, upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-FREE-003', contentVersion: 1,
      category: NabiNotificationCategory.milestone, priority: 800,
      policyKey: 'first_streak_7', audiences: _free,
      title: 'Bạn đã duy trì rất tốt',
      body: 'Mình cùng tiếp tục hành trình dài hơn nhé.',
      emotionKey: 'celebrating', primaryLabel: 'Tiếp tục với Plus',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_compare', planCode: 'plus', billingCycle: 'monthly'),
      secondaryLabel: 'Xem thành tích',
      secondaryDestination: NabiNotificationDestination(actionKey: 'achievement'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
      upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-FREE-004', contentVersion: 1,
      category: NabiNotificationCategory.contextual, priority: 1000,
      policyKey: 'expert_locked', audiences: _free,
      title: 'Bạn muốn hỏi chuyên gia?',
      body: 'Nabi sẽ giúp bạn xem quyền lợi hỗ trợ từ chuyên gia.',
      emotionKey: 'listening', primaryLabel: 'Xem quyền lợi chuyên gia',
      primaryDestination: NabiNotificationDestination(actionKey: 'expert_benefit'),
      secondaryLabel: 'Xem thông tin',
      secondaryDestination: NabiNotificationDestination(actionKey: 'expert_catalog'),
      channels: {NabiNotificationChannel.inApp}, proactive: false, upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-FREE-005', contentVersion: 1,
      category: NabiNotificationCategory.contextual, priority: 1000,
      policyKey: 'map365_locked', audiences: _free,
      title: 'Hành trình 365 đang chờ bạn',
      body: 'Mình xem trước các cột mốc và quyền lợi phù hợp nhé.',
      emotionKey: 'greeting', primaryLabel: 'Mở khóa Bản đồ 365',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_compare', planCode: 'plus', focus: 'map365'),
      secondaryLabel: 'Xem trước hành trình',
      secondaryDestination: NabiNotificationDestination(actionKey: 'map365'),
      channels: {NabiNotificationChannel.inApp}, proactive: false, upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-FREE-006', contentVersion: 1,
      category: NabiNotificationCategory.contextual, priority: 1000,
      policyKey: 'weekly_report_locked', audiences: _free,
      title: 'Báo cáo tuần đã sẵn sàng',
      body: 'Bản đầy đủ giúp bạn xem thói quen và gợi ý cho tuần tiếp theo.',
      emotionKey: 'thinking', primaryLabel: 'Xem báo cáo với Plus',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_compare', planCode: 'plus', focus: 'weekly_report'),
      secondaryLabel: 'Xem bản tóm tắt',
      secondaryDestination: NabiNotificationDestination(actionKey: 'weekly_report'),
      channels: {NabiNotificationChannel.inApp}, proactive: false, upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-FREE-007', contentVersion: 1,
      category: NabiNotificationCategory.contextual, priority: 1000,
      policyKey: 'expert_recommended', audiences: _free,
      title: 'Câu hỏi này cần thêm hỗ trợ',
      body: 'Nabi gợi ý bạn tham khảo chuyên gia để nhận hỗ trợ phù hợp hơn.',
      emotionKey: 'concerned', primaryLabel: 'Xem quyền lợi chuyên gia',
      primaryDestination: NabiNotificationDestination(actionKey: 'expert_benefit'),
      secondaryLabel: 'Để sau',
      secondaryDestination: NabiNotificationDestination(actionKey: 'defer'),
      channels: {NabiNotificationChannel.inApp}, proactive: false, upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-ANNUAL-001', contentVersion: 1,
      category: NabiNotificationCategory.subscription, priority: 500,
      policyKey: 'plus_day_7', audiences: _plusMonthly,
      title: 'Mình đi xa hơn cùng nhau nhé',
      body: 'Plus năm giúp Nabi đồng hành cùng bạn trọn vẹn hơn.',
      emotionKey: 'encouraging', primaryLabel: 'Xem Plus năm',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_compare', planCode: 'plus', billingCycle: 'yearly'),
      secondaryLabel: 'Xem hành trình hiện tại',
      secondaryDestination: NabiNotificationDestination(actionKey: 'dashboard_today'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
      upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-ANNUAL-002', contentVersion: 1,
      category: NabiNotificationCategory.subscription, priority: 500,
      policyKey: 'plus_day_15', audiences: _plusMonthly,
      title: 'Nabi đã hiểu bạn hơn một chút',
      body: 'Tiếp tục hành trình dài hạn sẽ giúp gợi ý ngày càng phù hợp.',
      emotionKey: 'listening', primaryLabel: 'Mở hành trình dài hạn',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_compare', planCode: 'plus', billingCycle: 'yearly'),
      secondaryLabel: 'Xem tiến trình',
      secondaryDestination: NabiNotificationDestination(actionKey: 'achievement'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
      upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-ANNUAL-003', contentVersion: 1,
      category: NabiNotificationCategory.subscription, priority: 900,
      policyKey: 'plus_expiry_5', audiences: _plusMonthly,
      title: 'Plus của bạn còn 5 ngày',
      body: 'Bạn có thể tiếp tục hành trình mà không bị gián đoạn.',
      emotionKey: 'reminder', primaryLabel: 'Tiếp tục với Plus năm',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_compare', planCode: 'plus', billingCycle: 'yearly'),
      secondaryLabel: 'Xem ngày hết hạn',
      secondaryDestination: NabiNotificationDestination(actionKey: 'subscription_detail'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
      upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-ANNUAL-004', contentVersion: 1,
      category: NabiNotificationCategory.subscription, priority: 900,
      policyKey: 'plus_expiry_1', audiences: _plusMonthly,
      title: 'Plus của bạn còn 1 ngày',
      body: 'Gia hạn hôm nay để tiếp tục hành trình cùng Nabi.',
      emotionKey: 'concerned', primaryLabel: 'Gia hạn ngay',
      primaryDestination: NabiNotificationDestination(
        actionKey: 'membership_payment', planCode: 'plus', billingCycle: 'yearly'),
      secondaryLabel: 'Để sau',
      secondaryDestination: NabiNotificationDestination(actionKey: 'defer'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
      upsell: true,
    ),
    NabiNotificationDefinition(
      id: 'NBI-STREAK-001', contentVersion: 1,
      category: NabiNotificationCategory.milestone, priority: 800,
      policyKey: 'streak_6', audiences: _allCare,
      title: 'Chỉ còn một bước nhỏ',
      body: 'Bạn đã duy trì 6 ngày. Mình hoàn thành việc nhỏ hôm nay nhé.',
      emotionKey: 'cheering', primaryLabel: 'Làm nhiệm vụ hôm nay',
      primaryDestination: NabiNotificationDestination(actionKey: 'easiest_task'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
    ),
    NabiNotificationDefinition(
      id: 'NBI-STREAK-002', contentVersion: 1,
      category: NabiNotificationCategory.reward, priority: 800,
      policyKey: 'rescue_card', audiences: _memberReward,
      title: 'Không sao, mình tiếp tục nhé',
      body: 'Bạn có một Thẻ cứu chuỗi hợp lệ để cân nhắc sử dụng.',
      emotionKey: 'concerned', primaryLabel: 'Dùng Thẻ cứu chuỗi',
      primaryDestination: NabiNotificationDestination(actionKey: 'rescue_card_confirm'),
      secondaryLabel: 'Để sau',
      secondaryDestination: NabiNotificationDestination(actionKey: 'defer'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
    ),
    NabiNotificationDefinition(
      id: 'NBI-REWARD-001', contentVersion: 1,
      category: NabiNotificationCategory.reward, priority: 800,
      policyKey: 'reward_ready', audiences: _memberReward,
      title: 'Một phần quà đang chờ bạn',
      body: 'Bạn đã đạt mốc {streak_days} ngày. {reward_name} đang chờ bạn mở.',
      emotionKey: 'celebrating', primaryLabel: 'Mở hộp quà',
      primaryDestination: NabiNotificationDestination(actionKey: 'reward_box'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
      requiredVariables: {'streak_days', 'reward_name'},
    ),
    NabiNotificationDefinition(
      id: 'NBI-REPORT-001', contentVersion: 1,
      category: NabiNotificationCategory.report, priority: 700,
      policyKey: 'report_ready', audiences: _memberReward,
      title: 'Báo cáo tuần đã sẵn sàng',
      body: 'Bạn có muốn xem Nabi nhận ra điều gì về thói quen tuần này không?',
      emotionKey: 'thinking', primaryLabel: 'Xem báo cáo',
      primaryDestination: NabiNotificationDestination(actionKey: 'weekly_report'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
    ),
    NabiNotificationDefinition(
      id: 'NBI-REFERRAL-001', contentVersion: 1,
      category: NabiNotificationCategory.retention, priority: 400,
      policyKey: 'invite_available', audiences: {'plus_yearly'},
      title: 'Mời người thân cùng bắt đầu',
      body: 'Bạn có thể tặng người thân 3 ngày trải nghiệm Plus.',
      emotionKey: 'happy', primaryLabel: 'Tặng trải nghiệm 3 ngày',
      primaryDestination: NabiNotificationDestination(actionKey: 'user_invite'),
      secondaryLabel: 'Xem quyền lợi',
      secondaryDestination: NabiNotificationDestination(actionKey: 'membership_compare'),
      channels: {NabiNotificationChannel.inApp},
    ),
    NabiNotificationDefinition(
      id: 'NBI-CARE-001', contentVersion: 1,
      category: NabiNotificationCategory.care, priority: 600,
      policyKey: 'care_near_sleep', audiences: _allCare,
      title: 'Hôm nay bạn bận lắm phải không?',
      body: 'Không sao, mình chỉ làm một nhiệm vụ nhỏ thôi nhé.',
      emotionKey: 'concerned', primaryLabel: 'Làm một nhiệm vụ nhỏ',
      primaryDestination: NabiNotificationDestination(actionKey: 'easiest_task'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
    ),
    NabiNotificationDefinition(
      id: 'NBI-CARE-002', contentVersion: 1,
      category: NabiNotificationCategory.care, priority: 600,
      policyKey: 'return_72h', audiences: _allCare,
      title: 'Nabi vui vì bạn đã quay lại',
      body: 'Mình tiếp tục từ một bước nhỏ hôm nay nhé?',
      emotionKey: 'greeting', primaryLabel: 'Tiếp tục hành trình',
      primaryDestination: NabiNotificationDestination(actionKey: 'dashboard_today'),
      channels: {NabiNotificationChannel.inApp},
    ),
    NabiNotificationDefinition(
      id: 'NBI-CARE-003', contentVersion: 1,
      category: NabiNotificationCategory.care, priority: 600,
      policyKey: 'partial_day', audiences: _allCare,
      title: 'Bạn không cần hoàn hảo',
      body: 'Mình chỉ cần tốt hơn hôm qua một chút thôi.',
      emotionKey: 'encouraging', primaryLabel: 'Bắt đầu lại hôm nay',
      primaryDestination: NabiNotificationDestination(actionKey: 'today_tasks'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
    ),
    NabiNotificationDefinition(
      id: 'NBI-PROFILE-001', contentVersion: 1,
      category: NabiNotificationCategory.profile, priority: 300,
      policyKey: 'profile_stale', audiences: _allCare,
      title: 'Mình cập nhật hồ sơ nhé',
      body: 'Dữ liệu mới giúp Nabi điều chỉnh gợi ý phù hợp hơn với bạn.',
      emotionKey: 'reminder', primaryLabel: 'Cập nhật hồ sơ',
      primaryDestination: NabiNotificationDestination(actionKey: 'partial_profile'),
      secondaryLabel: 'Để sau',
      secondaryDestination: NabiNotificationDestination(actionKey: 'defer'),
      channels: {NabiNotificationChannel.inApp, NabiNotificationChannel.osLocal},
    ),
  ];

  static String audienceKey(NabiBusinessSnapshot snapshot) {
    if (snapshot.actorKind == 'guest') return 'guest';
    if (snapshot.membershipPlan == 'family_plus') return 'family_plus';
    if (snapshot.membershipPlan == 'plus') {
      return snapshot.billingCycle == 'yearly' ? 'plus_yearly' : 'plus_monthly';
    }
    return 'free';
  }
}
