class MealPlansTable {
  static const tableName = 'meal_plans';

  static const createTable = '''
  CREATE TABLE meal_plans (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    plan_date TEXT,
    meal_type TEXT,
    meal_name TEXT,
    description TEXT,
    calories INTEGER,
    protein REAL,
    carbs REAL,
    fat REAL,
    fiber REAL,
    water_ml INTEGER,
    sugar_g REAL,
    saturated_fat_g REAL,
    sodium_mg REAL,
    cholesterol_mg REAL,
    potassium_mg REAL,
    calcium_mg REAL,
    iron_mg REAL,
    nutrition_status TEXT,
    meal_order INTEGER,
    start_time TEXT,
    end_time TEXT,
    cooking_instructions TEXT,
    catalog_code TEXT,
    serving_size TEXT,
    health_topic_code TEXT,
    health_topic_name TEXT,
    ingredients_json TEXT NOT NULL DEFAULT '[]',
    cooking_steps_json TEXT NOT NULL DEFAULT '[]',
    benefits TEXT,
    allergen_tags_json TEXT NOT NULL DEFAULT '[]',
    avoid_condition_tags_json TEXT NOT NULL DEFAULT '[]',
    source_name TEXT,
    source_hash TEXT,
    source_page INTEGER,
    snapshot_schema_version INTEGER NOT NULL DEFAULT 1,
    replacement_count INTEGER NOT NULL DEFAULT 0,
    is_completed INTEGER,
    ai_generated INTEGER,
    created_at TEXT,
    updated_at TEXT
  )
  ''';
}
