#!/usr/bin/env python3
"""Build or verify the canonical local/sandbox Supabase rebuild entrypoint."""

from __future__ import annotations

import argparse
from pathlib import Path


COMPONENTS = (
    "01_schema_rebuild_local_sandbox.sql",
    "02_schema_meal_nutrition_v18.sql",
    "03_schema_daily_health_hub_rewards.sql",
    "04_schema_auth_account_lock.sql",
    "05_seed_local_sandbox.sql",
    "06_schema_runtime_support.sql",
)
HEADER = """-- =============================================================================
-- config.sql
-- NanoBio Supabase canonical local/sandbox rebuild entrypoint.
--
-- DESTRUCTIVE LOCAL/SANDBOX SCRIPT ONLY. Do not run against staging or production.
-- Generated by tools/build_supabase_rebuild_config.py; do not edit by hand.
-- Source order:
-- {components}
-- =============================================================================
"""


def render(root: Path) -> str:
    supabase_dir = root / "docs" / "supabase"
    paths = tuple(supabase_dir / component for component in COMPONENTS)
    missing = [str(path) for path in paths if not path.is_file()]
    if missing:
        raise FileNotFoundError("Missing rebuild component(s):\n- " + "\n- ".join(missing))

    header = HEADER.format(components="\n-- ".join(COMPONENTS))
    sections = []
    for component, path in zip(COMPONENTS, paths):
        content = path.read_text(encoding="utf-8").rstrip()
        sections.append(f"-- BEGIN {component}\n\n{content}\n\n-- END {component}")
    return f"{header}\n" + "\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    output_path = root / "docs" / "supabase" / "config.sql"
    expected = render(root)
    actual = output_path.read_text(encoding="utf-8") if output_path.exists() else None

    if args.check:
        if actual != expected:
            raise SystemExit(
                "config.sql is stale. Run: python tools/build_supabase_rebuild_config.py"
            )
        print("PASS config.sql matches 01 through 06")
        return 0

    output_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {output_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
