import '../models/ai_catalog_models.dart';

class AiCatalogSeedData {
  static const _stamp = '2026-06-18T00:00:00.000';

  const AiCatalogSeedData._();

  static const meals = <MealCatalogItemModel>[
    MealCatalogItemModel(
      code: 'br_oat_egg',
      mealType: 'breakfast',
      mealName: 'Cháo yến mạch trứng gà',
      description: 'Bữa sáng giàu đạm, nhẹ bụng và hỗ trợ no lâu.',
      cookingInstructions:
          'Nấu yến mạch mềm với nước. Thêm trứng, rau xanh và nêm nhạt.',
      calories: 350,
      protein: 14,
      carbs: 45,
      fat: 9,
      fiber: 6,
      waterMl: 300,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'br_chicken_pho_light',
      mealType: 'breakfast',
      mealName: 'Phở gà nhẹ',
      description: 'Món nước ấm bụng, dễ ăn và cung cấp năng lượng ổn định.',
      cookingInstructions:
          'Dùng nước dùng ít béo. Thêm bánh phở, thịt gà xé và rau thơm.',
      calories: 390,
      protein: 24,
      carbs: 50,
      fat: 8,
      fiber: 3,
      waterMl: 350,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'br_brown_rice_egg',
      mealType: 'breakfast',
      mealName: 'Cơm gạo lứt trứng hấp',
      description: 'Bữa sáng chắc bụng, cân bằng tinh bột và đạm.',
      cookingInstructions:
          'Hấp trứng với hành lá. Ăn cùng cơm gạo lứt và dưa leo.',
      calories: 360,
      protein: 16,
      carbs: 48,
      fat: 10,
      fiber: 5,
      waterMl: 250,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'br_sweet_potato_yogurt',
      mealType: 'breakfast',
      mealName: 'Khoai lang sữa chua',
      description: 'Bữa sáng nhẹ, giàu chất xơ và tốt cho tiêu hóa.',
      cookingInstructions:
          'Hấp khoai lang chín mềm. Ăn cùng sữa chua không đường và hạt chia.',
      calories: 320,
      protein: 11,
      carbs: 52,
      fat: 6,
      fiber: 7,
      waterMl: 250,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'br_lotus_seed_porridge',
      mealType: 'breakfast',
      mealName: 'Cháo hạt sen thịt nạc',
      description: 'Món cháo mềm, dễ tiêu và phù hợp buổi sáng bận rộn.',
      cookingInstructions:
          'Nấu gạo với hạt sen đến mềm. Thêm thịt nạc băm và rau thơm.',
      calories: 370,
      protein: 18,
      carbs: 49,
      fat: 8,
      fiber: 4,
      waterMl: 300,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'br_tofu_noodle_soup',
      mealType: 'breakfast',
      mealName: 'Bún đậu hũ nước rau củ',
      description: 'Bữa sáng thanh nhẹ, có đạm thực vật và rau xanh.',
      cookingInstructions:
          'Nấu nước rau củ. Thêm bún, đậu hũ non và cải xanh thái nhỏ.',
      calories: 340,
      protein: 15,
      carbs: 47,
      fat: 7,
      fiber: 5,
      waterMl: 350,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'br_wholegrain_bread_egg',
      mealType: 'breakfast',
      mealName: 'Bánh mì nguyên cám trứng',
      description: 'Bữa sáng nhanh, đủ đạm và giúp giữ năng lượng lâu hơn.',
      cookingInstructions:
          'Áp chảo trứng ít dầu. Kẹp cùng bánh mì nguyên cám, xà lách và cà chua.',
      calories: 360,
      protein: 17,
      carbs: 42,
      fat: 11,
      fiber: 6,
      waterMl: 250,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'br_mung_bean_porridge',
      mealType: 'breakfast',
      mealName: 'Cháo đậu xanh bí đỏ',
      description: 'Món cháo dịu nhẹ, nhiều chất xơ và dễ ăn.',
      cookingInstructions:
          'Nấu đậu xanh, gạo và bí đỏ đến nhừ. Nêm nhạt và thêm hành lá.',
      calories: 330,
      protein: 12,
      carbs: 56,
      fat: 5,
      fiber: 8,
      waterMl: 300,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'ms_banana_yogurt',
      mealType: 'morning_snack',
      mealName: 'Chuối sữa chua không đường',
      description: 'Bữa phụ dịu bụng, bổ sung năng lượng vừa phải.',
      cookingInstructions:
          'Cắt chuối thành lát. Trộn với sữa chua không đường và ít hạt chia.',
      calories: 180,
      protein: 7,
      carbs: 30,
      fat: 3,
      fiber: 4,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'ms_guava_nuts',
      mealType: 'morning_snack',
      mealName: 'Ổi và hạt điều rang',
      description: 'Bữa phụ giòn nhẹ, giàu vitamin và chất béo tốt.',
      cookingInstructions:
          'Cắt ổi thành miếng vừa ăn. Dùng cùng một nắm nhỏ hạt điều rang nhạt.',
      calories: 190,
      protein: 5,
      carbs: 24,
      fat: 8,
      fiber: 6,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'ms_soy_milk',
      mealType: 'morning_snack',
      mealName: 'Sữa đậu nành ít đường',
      description: 'Bữa phụ giàu đạm thực vật, phù hợp khi cần ăn nhẹ.',
      cookingInstructions:
          'Hâm ấm sữa đậu nành. Dùng kèm vài lát táo nếu cần thêm năng lượng.',
      calories: 160,
      protein: 9,
      carbs: 18,
      fat: 5,
      fiber: 2,
      waterMl: 250,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'ms_dragonfruit_chia',
      mealType: 'morning_snack',
      mealName: 'Thanh long hạt chia',
      description: 'Bữa phụ mát nhẹ, hỗ trợ tiêu hóa và cấp nước.',
      cookingInstructions:
          'Cắt thanh long hạt lựu. Rắc hạt chia đã ngâm và dùng lạnh nhẹ.',
      calories: 150,
      protein: 4,
      carbs: 28,
      fat: 3,
      fiber: 6,
      waterMl: 220,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'ms_boiled_corn',
      mealType: 'morning_snack',
      mealName: 'Bắp luộc nhỏ',
      description: 'Bữa phụ no vừa, có chất xơ và vị ngọt tự nhiên.',
      cookingInstructions:
          'Luộc bắp đến chín mềm. Dùng một phần nhỏ, hạn chế thêm bơ hoặc muối.',
      calories: 170,
      protein: 5,
      carbs: 35,
      fat: 2,
      fiber: 4,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'ms_papaya_lime',
      mealType: 'morning_snack',
      mealName: 'Đu đủ chín vắt chanh',
      description: 'Bữa phụ ngọt nhẹ, nhiều vitamin và dễ tiêu.',
      cookingInstructions:
          'Cắt đu đủ chín thành miếng. Vắt vài giọt chanh và dùng ngay.',
      calories: 140,
      protein: 2,
      carbs: 32,
      fat: 1,
      fiber: 4,
      waterMl: 220,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'ms_apple_peanut',
      mealType: 'morning_snack',
      mealName: 'Táo và đậu phộng rang',
      description: 'Bữa phụ cân bằng vị ngọt, chất xơ và chất béo tốt.',
      cookingInstructions:
          'Cắt táo thành lát. Ăn cùng một muỗng nhỏ đậu phộng rang không muối.',
      calories: 190,
      protein: 5,
      carbs: 28,
      fat: 7,
      fiber: 5,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'ms_cucumber_hummus',
      mealType: 'morning_snack',
      mealName: 'Dưa leo chấm đậu gà',
      description: 'Bữa phụ thanh mát, ít năng lượng và có đạm thực vật.',
      cookingInstructions:
          'Cắt dưa leo dạng que. Chấm với sốt đậu gà xay nhuyễn nêm nhạt.',
      calories: 160,
      protein: 6,
      carbs: 18,
      fat: 6,
      fiber: 5,
      waterMl: 220,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'lu_brown_rice_salmon',
      mealType: 'lunch',
      mealName: 'Cơm gạo lứt cá hồi',
      description: 'Bữa trưa giàu đạm, chất béo tốt và rau xanh.',
      cookingInstructions:
          'Áp chảo cá hồi ít dầu. Ăn cùng cơm gạo lứt và rau luộc.',
      calories: 560,
      protein: 34,
      carbs: 58,
      fat: 18,
      fiber: 7,
      waterMl: 350,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'lu_chicken_vegetable_rice',
      mealType: 'lunch',
      mealName: 'Cơm ức gà rau củ',
      description: 'Bữa trưa dễ chuẩn bị, giàu đạm nạc và chất xơ.',
      cookingInstructions:
          'Luộc hoặc áp chảo ức gà. Dùng với cơm, bông cải và cà rốt hấp.',
      calories: 520,
      protein: 38,
      carbs: 60,
      fat: 10,
      fiber: 8,
      waterMl: 350,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'lu_tofu_mushroom_rice',
      mealType: 'lunch',
      mealName: 'Cơm đậu hũ nấm sốt nhạt',
      description: 'Bữa trưa thực vật nhẹ bụng, có đạm và khoáng chất.',
      cookingInstructions:
          'Kho đậu hũ với nấm và ít nước tương. Ăn cùng cơm và rau luộc.',
      calories: 480,
      protein: 22,
      carbs: 62,
      fat: 13,
      fiber: 8,
      waterMl: 350,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'lu_beef_vegetable_noodle',
      mealType: 'lunch',
      mealName: 'Bún bò rau cải',
      description: 'Bữa trưa ấm, đủ đạm và có rau xanh cân bằng.',
      cookingInstructions:
          'Nấu nước dùng nhạt. Thêm bún, thịt bò lát mỏng và rau cải.',
      calories: 540,
      protein: 32,
      carbs: 64,
      fat: 14,
      fiber: 5,
      waterMl: 380,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'lu_shrimp_soup_rice',
      mealType: 'lunch',
      mealName: 'Cơm canh tôm rau ngót',
      description: 'Bữa trưa thanh nhẹ, nhiều nước và dễ tiêu.',
      cookingInstructions:
          'Nấu canh tôm với rau ngót. Dùng cùng cơm trắng vừa phần.',
      calories: 500,
      protein: 28,
      carbs: 66,
      fat: 9,
      fiber: 6,
      waterMl: 400,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'lu_tuna_sweet_potato',
      mealType: 'lunch',
      mealName: 'Cá ngừ kho khoai lang',
      description: 'Bữa trưa no lâu, giàu đạm và tinh bột chậm.',
      cookingInstructions:
          'Kho cá ngừ nhạt với cà chua. Ăn cùng khoai lang hấp và rau xanh.',
      calories: 510,
      protein: 35,
      carbs: 55,
      fat: 12,
      fiber: 7,
      waterMl: 320,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'lu_lentil_veg_stew',
      mealType: 'lunch',
      mealName: 'Đậu lăng hầm rau củ',
      description: 'Bữa trưa giàu chất xơ, phù hợp ngày muốn ăn nhẹ thịt.',
      cookingInstructions: 'Hầm đậu lăng với bí đỏ, cà rốt và cà chua đến mềm.',
      calories: 470,
      protein: 24,
      carbs: 70,
      fat: 8,
      fiber: 12,
      waterMl: 350,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'lu_lean_pork_soup_rice',
      mealType: 'lunch',
      mealName: 'Cơm thịt nạc canh bí',
      description: 'Bữa trưa quen thuộc, dễ ăn và cân bằng năng lượng.',
      cookingInstructions:
          'Rim thịt nạc ít dầu. Nấu canh bí xanh và dùng cùng cơm vừa phần.',
      calories: 530,
      protein: 30,
      carbs: 64,
      fat: 13,
      fiber: 6,
      waterMl: 380,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'as_yogurt_chia',
      mealType: 'afternoon_snack',
      mealName: 'Sữa chua hạt chia',
      description: 'Bữa phụ mát nhẹ, hỗ trợ no vừa và tốt cho tiêu hóa.',
      cookingInstructions:
          'Ngâm hạt chia vài phút. Trộn với sữa chua không đường và ít trái cây.',
      calories: 170,
      protein: 8,
      carbs: 22,
      fat: 5,
      fiber: 5,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'as_steamed_sweet_potato',
      mealType: 'afternoon_snack',
      mealName: 'Khoai lang hấp',
      description: 'Bữa phụ no lâu, vị ngọt tự nhiên và giàu chất xơ.',
      cookingInstructions:
          'Hấp khoai lang đến mềm. Dùng phần vừa phải, không thêm đường.',
      calories: 180,
      protein: 3,
      carbs: 40,
      fat: 1,
      fiber: 5,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'as_green_smoothie',
      mealType: 'afternoon_snack',
      mealName: 'Sinh tố rau xanh chuối',
      description: 'Bữa phụ nhiều vitamin, dễ uống và bổ sung chất xơ.',
      cookingInstructions:
          'Xay chuối, cải bó xôi và sữa không đường. Uống ngay sau khi xay.',
      calories: 210,
      protein: 8,
      carbs: 34,
      fat: 5,
      fiber: 6,
      waterMl: 300,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'as_boiled_egg_tomato',
      mealType: 'afternoon_snack',
      mealName: 'Trứng luộc cà chua bi',
      description: 'Bữa phụ giàu đạm, gọn nhẹ và ít đường.',
      cookingInstructions:
          'Luộc trứng chín vừa. Ăn cùng cà chua bi rửa sạch và ít tiêu.',
      calories: 160,
      protein: 10,
      carbs: 8,
      fat: 9,
      fiber: 2,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'as_edamame',
      mealType: 'afternoon_snack',
      mealName: 'Đậu nành Nhật luộc',
      description: 'Bữa phụ giàu đạm thực vật, giúp no mà không nặng bụng.',
      cookingInstructions:
          'Luộc đậu nành Nhật đến chín. Rắc rất ít muối nếu cần.',
      calories: 190,
      protein: 14,
      carbs: 16,
      fat: 8,
      fiber: 6,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'as_orange_nuts',
      mealType: 'afternoon_snack',
      mealName: 'Cam và hạnh nhân',
      description: 'Bữa phụ tươi mát, có vitamin và chất béo tốt.',
      cookingInstructions:
          'Tách múi cam. Ăn cùng một nắm nhỏ hạnh nhân rang không muối.',
      calories: 190,
      protein: 5,
      carbs: 26,
      fat: 8,
      fiber: 5,
      waterMl: 220,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'as_oat_milk',
      mealType: 'afternoon_snack',
      mealName: 'Sữa yến mạch ít đường',
      description: 'Bữa phụ nhẹ, dễ uống và giúp ổn định cơn đói chiều.',
      cookingInstructions:
          'Dùng sữa yến mạch ít đường. Uống chậm cùng vài lát trái cây.',
      calories: 150,
      protein: 4,
      carbs: 25,
      fat: 4,
      fiber: 3,
      waterMl: 250,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'as_fresh_cheese_fruit',
      mealType: 'afternoon_snack',
      mealName: 'Phô mai tươi trái cây',
      description: 'Bữa phụ mềm nhẹ, có đạm và vị ngọt tự nhiên.',
      cookingInstructions:
          'Dùng phô mai tươi ít béo. Ăn cùng dâu hoặc xoài chín vừa phần.',
      calories: 200,
      protein: 11,
      carbs: 22,
      fat: 7,
      fiber: 3,
      waterMl: 200,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'di_fish_sour_soup_rice',
      mealType: 'dinner',
      mealName: 'Cơm canh chua cá',
      description: 'Bữa tối thanh nhẹ, nhiều rau và dễ tiêu.',
      cookingInstructions:
          'Nấu canh chua cá với cà chua, thơm và rau. Ăn cùng cơm vừa phần.',
      calories: 480,
      protein: 30,
      carbs: 58,
      fat: 10,
      fiber: 6,
      waterMl: 400,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'di_chicken_salad',
      mealType: 'dinner',
      mealName: 'Salad gà rau củ',
      description: 'Bữa tối giàu đạm, ít dầu và nhiều rau giòn.',
      cookingInstructions:
          'Xé ức gà luộc. Trộn với rau củ, dầu ô liu ít và nước chanh.',
      calories: 430,
      protein: 35,
      carbs: 28,
      fat: 16,
      fiber: 8,
      waterMl: 320,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'di_turmeric_tofu_soup',
      mealType: 'dinner',
      mealName: 'Canh đậu hũ nghệ rau xanh',
      description: 'Bữa tối ấm bụng, nhẹ nhàng và có đạm thực vật.',
      cookingInstructions:
          'Nấu đậu hũ với nghệ tươi và cải xanh. Nêm nhạt, dùng khi còn ấm.',
      calories: 390,
      protein: 20,
      carbs: 35,
      fat: 14,
      fiber: 7,
      waterMl: 380,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'di_pork_vegetable_roll',
      mealType: 'dinner',
      mealName: 'Cuốn thịt nạc rau sống',
      description: 'Bữa tối nhiều rau, no vừa và ít tinh bột.',
      cookingInstructions:
          'Luộc thịt nạc thái mỏng. Cuốn với rau sống, bún ít và chấm nhạt.',
      calories: 450,
      protein: 28,
      carbs: 42,
      fat: 14,
      fiber: 7,
      waterMl: 320,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'di_shrimp_glass_noodle',
      mealType: 'dinner',
      mealName: 'Miến tôm rau cải',
      description: 'Bữa tối nhẹ, có nước dùng và đạm từ tôm.',
      cookingInstructions:
          'Nấu nước dùng nhạt. Thêm miến, tôm bóc vỏ và rau cải.',
      calories: 420,
      protein: 26,
      carbs: 52,
      fat: 8,
      fiber: 5,
      waterMl: 380,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'di_mushroom_congee',
      mealType: 'dinner',
      mealName: 'Cháo nấm rau củ',
      description: 'Bữa tối mềm, dễ tiêu và phù hợp khi muốn ăn nhẹ.',
      cookingInstructions:
          'Nấu cháo loãng với nấm, cà rốt và cải xanh. Nêm nhạt.',
      calories: 360,
      protein: 12,
      carbs: 60,
      fat: 6,
      fiber: 7,
      waterMl: 380,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'di_lean_beef_soup',
      mealType: 'dinner',
      mealName: 'Canh thịt bò rau củ',
      description: 'Bữa tối ấm, đủ đạm và nhiều rau củ mềm.',
      cookingInstructions:
          'Nấu thịt bò lát mỏng với cà rốt, bí xanh và hành lá.',
      calories: 440,
      protein: 32,
      carbs: 34,
      fat: 15,
      fiber: 6,
      waterMl: 400,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    MealCatalogItemModel(
      code: 'di_egg_tomato_soup',
      mealType: 'dinner',
      mealName: 'Canh trứng cà chua',
      description: 'Bữa tối đơn giản, dịu nhẹ và dễ chuẩn bị.',
      cookingInstructions:
          'Nấu cà chua với nước dùng nhạt. Khuấy trứng vào cuối và thêm hành.',
      calories: 370,
      protein: 18,
      carbs: 38,
      fat: 13,
      fiber: 4,
      waterMl: 380,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
  ];

  static const exercises = <ExerciseCatalogItemModel>[
    ExerciseCatalogItemModel(
      code: 'ex_walk_relaxed',
      category: 'body',
      title: 'Đi bộ thư giãn',
      description: 'Đi bộ chậm, giữ nhịp thở đều và thả lỏng vai.',
      unit: 'lần',
      encouragement: 'Bạn đang giúp cơ thể tỉnh táo hơn từng chút.',
      minTarget: 1,
      maxTarget: 1,
      defaultTarget: 1,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_mobility_shoulder',
      category: 'body',
      title: 'Xoay vai nhẹ',
      description: 'Xoay vai chậm theo vòng tròn, giữ cổ thư giãn.',
      unit: 'lần',
      encouragement: 'Vai cổ được thả lỏng là một khởi đầu rất tốt.',
      minTarget: 1,
      maxTarget: 2,
      defaultTarget: 1,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_chair_squat',
      category: 'body',
      title: 'Đứng ngồi với ghế',
      description: 'Ngồi xuống ghế rồi đứng lên chậm, giữ lưng thẳng.',
      unit: 'lần',
      encouragement: 'Mỗi lần đứng lên là một điểm cộng cho sức bền.',
      minTarget: 8,
      maxTarget: 16,
      defaultTarget: 10,
      intensityLevel: 'moderate',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_breathing_stretch',
      category: 'body',
      title: 'Vươn vai theo nhịp thở',
      description: 'Hít sâu khi vươn tay, thở ra khi hạ tay chậm.',
      unit: 'lần',
      encouragement: 'Nhịp thở đều giúp cơ thể dịu lại nhanh hơn.',
      minTarget: 1,
      maxTarget: 3,
      defaultTarget: 1,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_wall_push',
      category: 'body',
      title: 'Chống đẩy tường',
      description: 'Đặt tay lên tường, hạ người chậm rồi đẩy về vị trí cũ.',
      unit: 'lần',
      encouragement: 'Bạn đang tăng sức mạnh rất an toàn và vừa sức.',
      minTarget: 8,
      maxTarget: 18,
      defaultTarget: 10,
      intensityLevel: 'moderate',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_calf_raise',
      category: 'body',
      title: 'Nhón gót tại chỗ',
      description: 'Đứng thẳng, nhón gót chậm rồi hạ xuống có kiểm soát.',
      unit: 'lần',
      encouragement: 'Bắp chân được đánh thức nhẹ nhàng rồi đó.',
      minTarget: 10,
      maxTarget: 24,
      defaultTarget: 15,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_yoga_cat_cow',
      category: 'body',
      title: 'Mèo bò nhẹ',
      description: 'Cong và võng lưng chậm, phối hợp nhịp thở đều.',
      unit: 'lần',
      encouragement: 'Lưng của bạn vừa có thêm một khoảng thư giãn.',
      minTarget: 6,
      maxTarget: 14,
      defaultTarget: 8,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_step_march',
      category: 'body',
      title: 'Bước tại chỗ',
      description: 'Nâng gối thấp, đánh tay nhẹ và giữ thân người ổn định.',
      unit: 'phút',
      encouragement: 'Nhịp vận động nhỏ cũng giúp ngày hôm nay sáng hơn.',
      minTarget: 3,
      maxTarget: 10,
      defaultTarget: 5,
      intensityLevel: 'moderate',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_neck_release',
      category: 'body',
      title: 'Thả lỏng cổ',
      description: 'Nghiêng cổ nhẹ sang hai bên, không ép quá biên độ.',
      unit: 'lần',
      encouragement: 'Bạn vừa giảm bớt căng cứng cho vùng cổ vai.',
      minTarget: 1,
      maxTarget: 2,
      defaultTarget: 1,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_hip_open',
      category: 'body',
      title: 'Mở hông nhẹ',
      description: 'Ngồi thẳng, xoay hông chậm và giữ hơi thở thoải mái.',
      unit: 'lần',
      encouragement: 'Khớp hông linh hoạt hơn sẽ giúp bạn di chuyển êm hơn.',
      minTarget: 1,
      maxTarget: 2,
      defaultTarget: 1,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_core_breath',
      category: 'body',
      title: 'Siết bụng theo thở',
      description: 'Hít sâu, thở ra chậm và siết bụng nhẹ trong vài giây.',
      unit: 'lần',
      encouragement: 'Bạn đang tập trung vào lõi cơ thể rất đúng cách.',
      minTarget: 6,
      maxTarget: 14,
      defaultTarget: 8,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_balance_stand',
      category: 'body',
      title: 'Đứng thăng bằng',
      description: 'Đứng gần tường, nhấc một chân thấp và đổi bên chậm.',
      unit: 'lần',
      encouragement: 'Thăng bằng tốt hơn giúp cơ thể tự tin hơn.',
      minTarget: 1,
      maxTarget: 2,
      defaultTarget: 1,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_light_dance',
      category: 'body',
      title: 'Lắc người nhẹ',
      description: 'Bật nhạc chậm, lắc người nhẹ và giữ nhịp thở tự nhiên.',
      unit: 'phút',
      encouragement: 'Một chút vui vẻ cũng là chăm sóc sức khỏe.',
      minTarget: 3,
      maxTarget: 8,
      defaultTarget: 5,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_stair_slow',
      category: 'body',
      title: 'Lên xuống bậc thấp',
      description: 'Bước lên bậc thấp chậm, bám tay vịn nếu cần.',
      unit: 'lần',
      encouragement: 'Bạn đang tăng sức bền từng bước rất chắc chắn.',
      minTarget: 6,
      maxTarget: 16,
      defaultTarget: 8,
      intensityLevel: 'moderate',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_back_stretch',
      category: 'body',
      title: 'Giãn lưng ngồi',
      description: 'Ngồi thẳng, cúi nhẹ người về trước và thả lỏng lưng.',
      unit: 'lần',
      encouragement: 'Lưng được nghỉ một nhịp, bạn cũng vậy.',
      minTarget: 1,
      maxTarget: 3,
      defaultTarget: 1,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ExerciseCatalogItemModel(
      code: 'ex_tai_chi',
      category: 'body',
      title: 'Thái cực quyền chậm',
      description: 'Di chuyển tay chân chậm, mềm và giữ hơi thở đều.',
      unit: 'phút',
      encouragement: 'Chuyển động chậm giúp cơ thể và tâm trí cùng dịu lại.',
      minTarget: 3,
      maxTarget: 10,
      defaultTarget: 5,
      intensityLevel: 'light',
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
  ];

  static const scheduleTasks = <ScheduleTaskCatalogItemModel>[
    ScheduleTaskCatalogItemModel(
      code: 'routine_wake',
      category: 'wake',
      title: 'Thức dậy',
      description: 'Bắt đầu ngày mới, ngồi dậy chậm và giãn cơ nhẹ.',
      startTime: '06:00',
      endTime: '06:15',
      targetValue: 1,
      unit: 'lần',
      encouragement: 'Một khởi đầu chậm rãi giúp cả ngày dễ chịu hơn.',
      sortOrder: 1,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ScheduleTaskCatalogItemModel(
      code: 'routine_water_morning',
      category: 'water',
      title: 'Uống nước đầu ngày',
      description: 'Uống một cốc nước nhỏ để khởi động cơ thể.',
      startTime: '06:15',
      endTime: '06:20',
      targetValue: 250,
      unit: 'ml',
      encouragement: 'Cơ thể vừa được tiếp nước rất đúng lúc.',
      sortOrder: 2,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
    ScheduleTaskCatalogItemModel(
      code: 'routine_sleep_prepare',
      category: 'sleep',
      title: 'Chuẩn bị ngủ',
      description: 'Giảm ánh sáng màn hình và chuẩn bị ngủ đúng giờ.',
      startTime: '21:00',
      endTime: '21:15',
      targetValue: 1,
      unit: 'lần',
      encouragement: 'Bạn đang đặt nền cho một giấc ngủ tử tế.',
      sortOrder: 10,
      createdAt: _stamp,
      updatedAt: _stamp,
    ),
  ];
}
